
local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local beastBreathingFolder = animationsFolder:WaitForChild("BeastBreathing")
local ExplosiveRushRun = beastBreathingFolder:WaitForChild("ExplosiveRushRun")

if ExplosiveRushRun:IsA("Animation") then
    ExplosiveRushRun.AnimationId = "rbxassetid://14657259011"
end


----
local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local Sprint = animationsFolder:WaitForChild("Sprint")

if Sprint:IsA("Animation") then
    Sprint.AnimationId = "rbxassetid://14657259011"
end

--------------------
local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local beastBreathingFolder = animationsFolder:WaitForChild("ChippedKatanas")
local ExplosiveRushRun = beastBreathingFolder:WaitForChild("Run")

if ExplosiveRushRun:IsA("Animation") then
    ExplosiveRushRun.AnimationId = "rbxassetid://14657259011"
end

----------
local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local beastBreathingFolder = animationsFolder:WaitForChild("ChippedKatanas")
local ExplosiveRushRun = beastBreathingFolder:WaitForChild("Heavy")

if ExplosiveRushRun:IsA("Animation") then
    ExplosiveRushRun.AnimationId = "rbxassetid://11534464124"
end

-----------------------
local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local beastBreathingFolder = animationsFolder:WaitForChild("BeastBreathing")
local ExplosiveRushRun = beastBreathingFolder:WaitForChild("ExplosiveRushStart")

if ExplosiveRushRun:IsA("Animation") then
    ExplosiveRushRun.AnimationId = "rbxassetid://13287329762"
end

-----------

local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local beastBreathingFolder = animationsFolder:WaitForChild("BeastBreathing")
local ExplosiveRushRun = beastBreathingFolder:WaitForChild("PallisadeBiteHit")

if ExplosiveRushRun:IsA("Animation") then
    ExplosiveRushRun.AnimationId = "rbxassetid://13340668144"
end

---------------------

local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local beastBreathingFolder = animationsFolder:WaitForChild("BeastBreathing")
local ExplosiveRushRun = beastBreathingFolder:WaitForChild("ExplosiveRushRun")

if ExplosiveRushRun:IsA("Animation") then
    ExplosiveRushRun.AnimationId = "rbxassetid://14657259011"
end

-------------------

local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local beastBreathingFolder = animationsFolder:WaitForChild("BeastBreathing")
local ExplosiveRushRun = beastBreathingFolder:WaitForChild("CrazyCuttingEscape")

if ExplosiveRushRun:IsA("Animation") then
    ExplosiveRushRun.AnimationId = "rbxassetid://15457108835"
end

-------------------

local replicatedStorage = game:GetService("ReplicatedStorage")
local animationsFolder = replicatedStorage:WaitForChild("Animations")
local beastBreathingFolder = animationsFolder:WaitForChild("BeastBreathing")
local ExplosiveRushRun = beastBreathingFolder:WaitForChild("Devour")

if ExplosiveRushRun:IsA("Animation") then
    ExplosiveRushRun.AnimationId = "rbxassetid://13256435512"
end
